[tool.poetry]
name = "comms-utilities"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "3.10.5"
pyairtable = "^1.3.0"
click = "^8.1.3"
Jinja2 = "^3.1.2"
google-api-python-client = "^2.58.0"
google-auth-oauthlib = "^0.5.2"
boto3 = "^1.24.64"
requests-toolbelt = "^0.9.1"
rollbar = "^0.16.3"
pytz = "^2022.2"
churchsuite = {git = "https://github.com/whitkirkchurch/churchsuite-utilities", rev = "v0.1.0"}

[tool.poetry.dev-dependencies]
coverage = "^6.4.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
