[tool.poetry]
name = "streaming-utilities"
version = "0.1.0"
description = "A set of utilities to help us manage our streaming services"
authors = ["St Mary's Church, Whitkirk <tech@whitkirkchurch.org.uk>"]
package-mode = false

[tool.poetry.dependencies]
python = "==3.13.7"
pyairtable = "^1.3.0"
click = "^8.1.3"
Jinja2 = "^3.1.2"
google-api-python-client = "^2.79.0"
google-auth-oauthlib = "^1.0.0"
boto3 = "^1.26.97"
requests-toolbelt = "^1.0.0"
rollbar = "^1.0.0"
pytz = "^2025.0"
churchsuite = {git = "https://github.com/whitkirkchurch/churchsuite-utilities.git", rev = "b69f52ab77a26717ef520ffe020b8a34f72a242b"}
pytest = "^9.0.0"
pillow = "^12.0.0"

[tool.poetry.group.dev.dependencies]
coverage = "7.13.4"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
