[tool.poetry]
name = "comms-utilities"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "3.8.12"
pyairtable = "^1.0.0"
click = "^8.0.3"
Jinja2 = "^3.0.3"
google-api-python-client = "^2.36.0"
google-auth-oauthlib = "^0.4.6"
boto3 = "^1.21.5"
requests-toolbelt = "^0.9.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
